[theme]
base = "dark"
primaryColor = "#e08d6d"
backgroundColor = "#0b0710"
secondaryBackgroundColor = "#1c1119"
textColor = "#f2e8dc"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
enableStaticServing = true
